<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>

        {{ $title }}

    </title>

    <style>

        *{
            margin:0;
            padding:0;
            box-sizing:border-box;
        }

        body{

            font-family: DejaVu Sans, sans-serif;
            font-size:12px;
            color:#333;
            padding:25px;

        }

        .header{

            text-align:center;
            margin-bottom:25px;
            border-bottom:2px solid #0f766e;
            padding-bottom:15px;

        }

        .header h1{

            font-size:24px;
            color:#0f766e;
            margin-bottom:6px;

        }

        .header p{

            font-size:13px;
            color:#666;

        }

        .report-info{

            margin-bottom:20px;

        }

        .report-info table{

            width:100%;

        }

        .report-info td{

            padding:5px 0;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        thead{

            background:#0f766e;
            color:#fff;

        }

        th{

            border:1px solid #ddd;
            padding:10px 8px;
            text-align:left;
            font-size:11px;

        }

        td{

            border:1px solid #ddd;
            padding:8px;
            font-size:10px;

        }

        tbody tr:nth-child(even){

            background:#f8f8f8;

        }

        .footer{

            position:fixed;
            bottom:10px;
            left:0;
            right:0;

            text-align:center;

            font-size:10px;

            color:#777;

            border-top:1px solid #ddd;

            padding-top:8px;

        }

    </style>

</head>

<body>

<div class="header">

    <h1>

        ☀ Solar Management System

    </h1>

    <p>

        {{ $title }}

    </p>

</div>

<div class="report-info">

    <table>

        <tr>

            <td>

                <strong>Module :</strong>

                {{ $module }}

            </td>

            <td align="right">

                <strong>Generated :</strong>

                {{ $generatedAt->format('d M Y h:i A') }}

            </td>

        </tr>

        <tr>

            <td>

                <strong>Total Records :</strong>

                {{ $rows->count() }}

            </td>

            <td align="right">

                <strong>Generated By :</strong>

                Solar Management System

            </td>

        </tr>

    </table>

</div>

@yield('content')

<div class="footer">

    © {{ date('Y') }}

    Solar Management System |

    Developed By Maaz Khan

</div>

</body>

</html>