<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>

        {{ $title }}

    </title>

    <style>

        *{

            margin:0;
            padding:0;
            box-sizing:border-box;

        }

        body{

            font-family: DejaVu Sans, sans-serif;
            font-size:12px;
            color:#333;
            padding:25px;

        }

        .header{

            text-align:center;
            margin-bottom:25px;

        }

        .header h1{

            font-size:24px;
            color:#0f766e;
            margin-bottom:8px;

        }

        .header p{

            color:#666;
            font-size:13px;

        }

        .report-info{

            margin-bottom:20px;

        }

        .report-info table{

            width:100%;

        }

        .report-info td{

            padding:4px 0;

        }

        table{

            width:100%;
            border-collapse:collapse;

        }

        thead{

            background:#0f766e;
            color:#fff;

        }

        th{

            border:1px solid #ddd;
            padding:10px 6px;
            font-size:11px;
            text-align:left;

        }

        td{

            border:1px solid #ddd;
            padding:8px 6px;
            font-size:10px;

        }

        tbody tr:nth-child(even){

            background:#f8f8f8;

        }

        .footer{

            margin-top:25px;
            text-align:center;
            color:#888;
            font-size:11px;

        }

    </style>

</head>

<body>

<div class="header">

    <h1>

        ☀ Solar Management System

    </h1>

    <p>

        {{ $title }}

    </p>

</div>

<div class="report-info">

    <table>

        <tr>

            <td>

                <strong>Module :</strong>

                {{ $module }}

            </td>

            <td align="right">

                <strong>Date :</strong>

                {{ now()->format('d M Y h:i A') }}

            </td>

        </tr>

        <tr>

            <td>

                <strong>Total Records :</strong>

                {{ count($rows) }}

            </td>

            <td align="right">

                <strong>Generated By :</strong>

                Solar Management System

            </td>

        </tr>

    </table>

</div>

<table>

    <thead>

        <tr>

            @if(count($rows) > 0)

                @foreach(array_keys($rows[0]->toArray()) as $column)

                    <th>

                        {{ ucwords(str_replace("_"," ",$column)) }}

                    </th>

                @endforeach

            @endif

        </tr>

    </thead>

    <tbody>

        @forelse($rows as $row)

            <tr>

                @foreach($row->toArray() as $value)

                    <td>

                        @if(is_array($value))

                            {{ json_encode($value) }}

                        @else

                            {{ $value }}

                        @endif

                    </td>

                @endforeach

            </tr>

        @empty

            <tr>

                <td colspan="20" align="center">

                    No Data Available

                </td>

            </tr>

        @endforelse

    </tbody>

</table>

<div class="footer">

    © {{ date('Y') }}

    Solar Management System |

    Developed By Maaz Khan

</div>

</body>

</html>